import express from "express";

import {
  googleLogin,
} from "../../controllers/auth/googleAuthController.js";

const router = express.Router();

// ============================================================
// GOOGLE CLIENT-ID AUTHENTICATION
// ============================================================
//
// POST /api/auth/google
//
// Body:
// {
//   credential: "GOOGLE_ID_TOKEN"
// }
//
// The credential is generated by:
//
// @react-oauth/google
//
// The backend verifies it using:
//
// GOOGLE_CLIENT_ID
//
// ============================================================

router.post(
  "/google",
  googleLogin
);

export default router;
